// AUTO-GENERATED by scripts/gen-assets.mjs — do not edit.
export const CARD_IMAGE_FILES: Record<string, string> = {};
export const CARD_BG_BY_LEVEL_COLOR: Record<string, string> = {
  "1_black": "L1_Black_Onyx.webp",
  "1_blue": "L1_Blue_Sapphire.webp",
  "1_green": "L1_Green_Emerald.webp",
  "1_red": "L1_Red_Ruby.webp",
  "1_white": "L1_White_Diamond.webp",
  "2_black": "L2_Black_Onyx.webp",
  "2_blue": "L2_Blue_Sapphire.webp",
  "2_green": "L2_Green_Emerald.webp",
  "2_red": "L2_Red_Ruby.webp",
  "2_white": "L2_White_Diamond.webp",
  "3_black": "L3_Black_Onyx.webp",
  "3_blue": "L3_Blue_Sapphire.webp",
  "3_green": "L3_Green_Emerald.webp",
  "3_red": "L3_Red_Ruby.webp",
  "3_white": "L3_White_Diamond.webp"
};
export const CARD_BACK_BY_LEVEL: Record<string, string> = {
  "1": "CardBack_Level1.webp",
  "2": "CardBack_Level2.webp",
  "3": "CardBack_Level3.webp"
};
export const NOBLE_IMAGE_FILES: Record<string, string> = {};
export const NOBLE_BG: string | null = "Noble_Tile_Background.webp";
