// AUTO-GENERATED by scripts/gen-assets.mjs — do not edit.
// Maps id -> image filename for user-supplied art in public/cards and public/nobles.
export const CARD_IMAGE_FILES: Record<string, string> = {};
export const NOBLE_IMAGE_FILES: Record<string, string> = {};
