/* Scans public/cards and public/nobles for user-supplied images and writes
   lib/assets.ts mapping id -> filename. Run via `npm run assets` (also runs
   automatically on predev/prebuild). Missing images fall back to pixel art. */
import { readdirSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join, parse } from "node:path";

const ROOT = process.cwd();
const EXTS = new Set([".png", ".jpg", ".jpeg", ".webp", ".gif", ".avif"]);

function scan(dir) {
  const abs = join(ROOT, "public", dir);
  if (!existsSync(abs)) {
    mkdirSync(abs, { recursive: true });
    return {};
  }
  const map = {};
  for (const f of readdirSync(abs)) {
    const { name, ext } = parse(f);
    if (!EXTS.has(ext.toLowerCase())) continue; // skip README.md etc.
    map[name] = f; // id -> filename (with extension)
  }
  return map;
}

const cards = scan("cards");
const nobles = scan("nobles");

const out = `// AUTO-GENERATED by scripts/gen-assets.mjs — do not edit.
// Maps id -> image filename for user-supplied art in public/cards and public/nobles.
export const CARD_IMAGE_FILES: Record<string, string> = ${JSON.stringify(cards, null, 2)};
export const NOBLE_IMAGE_FILES: Record<string, string> = ${JSON.stringify(nobles, null, 2)};
`;

writeFileSync(join(ROOT, "lib", "assets.ts"), out);
console.log(
  `assets: ${Object.keys(cards).length} card image(s), ${Object.keys(nobles).length} noble image(s)`,
);
