/* Scans public/cards and public/nobles for user-supplied images and writes
   lib/assets.ts. Recognizes:
   - per-card art:   <cardId>.<ext>            (e.g. L1-001.png)
   - per-level+color: L<level>_<Color>_*.<ext> (e.g. L1_White_Diamond.webp)
   - card backs:     CardBack_Level<n>.<ext>
   - per-noble art:  <nobleId>.<ext>           (e.g. N-01.png)
   - noble backdrop: Noble_Tile_Background.<ext> (in public/nobles)
   Run via `npm run assets` (also runs on predev/prebuild). */
import { readdirSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join, parse } from "node:path";

const ROOT = process.cwd();
const EXTS = new Set([".png", ".jpg", ".jpeg", ".webp", ".gif", ".avif"]);

function listImages(dir) {
  const abs = join(ROOT, "public", dir);
  if (!existsSync(abs)) {
    mkdirSync(abs, { recursive: true });
    return [];
  }
  return readdirSync(abs).filter((f) => EXTS.has(parse(f).ext.toLowerCase()));
}

const cardById = {};
const cardByLevelColor = {};
const cardBackByLevel = {};
const nobleById = {};
let nobleBg = null;

for (const f of listImages("cards")) {
  const name = parse(f).name; // filename without extension
  let m;
  if ((m = /^L([123])-\d+$/i.exec(name))) {
    cardById[name] = f;
  } else if ((m = /^L([123])_([A-Za-z]+)_/i.exec(name))) {
    cardByLevelColor[`${m[1]}_${m[2].toLowerCase()}`] = f;
  } else if ((m = /^CardBack_Level([123])/i.exec(name))) {
    cardBackByLevel[m[1]] = f;
  }
}

for (const f of listImages("nobles")) {
  const name = parse(f).name;
  if (/^N-\d+$/i.exec(name)) nobleById[name] = f;
  else if (/noble.*background/i.test(name)) nobleBg = f;
}

// Gem/coin token images: public/gem/Gem_<Color>_*.<ext>  (Gold -> gold)
const gemImages = {};
for (const f of listImages("gem")) {
  const m = /^Gem_([A-Za-z]+)/i.exec(parse(f).name);
  if (m) gemImages[m[1].toLowerCase()] = f;
}

const out = `// AUTO-GENERATED by scripts/gen-assets.mjs — do not edit.
export const CARD_IMAGE_FILES: Record<string, string> = ${JSON.stringify(cardById, null, 2)};
export const CARD_BG_BY_LEVEL_COLOR: Record<string, string> = ${JSON.stringify(cardByLevelColor, null, 2)};
export const CARD_BACK_BY_LEVEL: Record<string, string> = ${JSON.stringify(cardBackByLevel, null, 2)};
export const NOBLE_IMAGE_FILES: Record<string, string> = ${JSON.stringify(nobleById, null, 2)};
export const NOBLE_BG: string | null = ${JSON.stringify(nobleBg)};
export const GEM_IMAGE_FILES: Record<string, string> = ${JSON.stringify(gemImages, null, 2)};
`;

writeFileSync(join(ROOT, "lib", "assets.ts"), out);
console.log(
  `assets: ${Object.keys(cardById).length} per-card, ${Object.keys(cardByLevelColor).length} level+color, ` +
    `${Object.keys(cardBackByLevel).length} backs, ${Object.keys(nobleById).length} noble, bg=${nobleBg ? "yes" : "no"}`,
);
